version: "3.4"

services:
    boiler:
        build:
            context: ./
        ports:
            - "3000:80"
        container_name: boiler
        restart: always
    nginx:
        container_name: nginx
        restart: always
        build:
            context: ./nginx-certbot
            args:
                DOMAIN: server.company.com
        environment:
            CERTBOT_EMAIL: example.email@something.com
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./data/certs:/etc/letsencrypt
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: example
        volumes:
            - ./data/db:/var/lib/postgresql/data
        ports:
            - 5432:5432
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
