version: '3.4'

services:
  netcore-postgres-oauth-boiler:
    image: ${DOCKER_REGISTRY-}netcorepostgresoauthboiler
    build:
      context: .
      dockerfile: Dockerfile
  # nginx:
  #   container_name: nginx
  #   restart: always
  #   build:
  #     context: ./nginx-certbot
  #   environment:
  #     - CERTBOT_EMAIL=someEmail@example.com
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./data/certs:/etc/letsencrypt
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
#  pgadmin:
#    image: dpage/pgadmin4
#    restart: unless-stopped
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#    volumes:
#       - pgadmin:/root/.pgadmin
#    ports:
#      - 8080:80
volumes:
  db:
    external: true
